### ISSUE TITLE
Learning new tools checklist

### ISSUE THREAD

**Issue by paigem** [leoberhelman/ACCESS-NRI-Internship#2]
- [x] JupyterLab? 
- [x] Xarray 
  - [x] Read through Xarray’s [Getting Started](https://docs.xarray.dev/en/stable/getting-started-guide/index.html). Read the following sections: 
    - [x] Overview: Why xarray? 
    - [x] Quick overview 
    - [x] Frequently Asked Questions 
  - [x] Go through the Xarray tutorial “Xarray in 45 minutes” 
- [x] Dask 
  - [x] [Youtube video: Dask in 8 Minutes](https://www.youtube.com/watch?v=nnndxbr_Xq4)  
  - [x] [Youtube video: Dask Delayed in 5 Minutes](https://www.youtube.com/watch?v=SHqFmynRxVU) 
  - [x] [Dask Tutorial](https://tutorial.dask.org/00_overview.html)
